# Generated by Django 5.2.15 on 2026-07-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_progress_stage_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='campaign_link',
            field=models.URLField(blank=True, verbose_name='Link camp'),
        ),
        migrations.AddField(
            model_name='project',
            name='registration_link_1',
            field=models.URLField(blank=True, verbose_name='Link đăng ký 1'),
        ),
        migrations.AddField(
            model_name='project',
            name='registration_link_2',
            field=models.URLField(blank=True, verbose_name='Link đăng ký 2'),
        ),
        migrations.AddField(
            model_name='project',
            name='registration_link_3',
            field=models.URLField(blank=True, verbose_name='Link đăng ký 3'),
        ),
    ]
