# Generated by Django 5.2.15 on 2026-07-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_campaign_link_project_registration_link_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='registration_link_1',
            field=models.URLField(blank=True, verbose_name='Link đăng ký'),
        ),
    ]
