# Generated by Django 5.2.15 on 2026-07-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_progress_stage_alter_task_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_note',
            field=models.TextField(blank=True, verbose_name='Ghi chú cập nhật'),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress_stage',
            field=models.CharField(blank=True, max_length=30, verbose_name='Trạng thái tiến trình'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Chưa giao'), ('assigned', 'Đã giao'), ('in_progress', 'Đang làm'), ('blocked', 'Vướng mắc'), ('done', 'Hoàn thành')], default='unassigned', max_length=30, verbose_name='Trạng thái'),
        ),
    ]
