# Generated by Django 5.2.15 on 2026-07-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['full_name', 'email']},
        ),
    ]
