# Generated by Django 5.2.15 on 2026-07-08 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_in_file', models.PositiveIntegerField(default=0)),
                ('duplicate_in_system', models.PositiveIntegerField(default=0)),
                ('imported_success', models.PositiveIntegerField(default=0)),
                ('committed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_value', models.TextField()),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_duplicate_file', models.BooleanField(default=False)),
                ('is_duplicate_system', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('existing_project_id', models.PositiveIntegerField(blank=True, null=True)),
                ('imported_project_id', models.PositiveIntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importsession')),
            ],
        ),
    ]
