# Generated by Django 5.2.15 on 2026-07-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('in_app', 'Trong hệ thống'), ('telegram', 'Telegram'), ('both', 'Hệ thống + Telegram')], default='in_app', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('task_assigned', 'Giao công việc'), ('task_updated', 'Cập nhật công việc'), ('task_blocked', 'Công việc vướng mắc'), ('task_done', 'Hoàn thành công việc'), ('task_reviewed', 'Duyệt công việc'), ('task_deadline', 'Nhắc deadline công việc'), ('project_assigned', 'Giao dự án'), ('project_updated', 'Cập nhật dự án'), ('project_deadline', 'Nhắc deadline dự án'), ('system', 'Hệ thống')], default='system', max_length=40),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Thấp'), ('normal', 'Bình thường'), ('high', 'Quan trọng')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='telegram_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='telegram_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
